"""add_placement_to_submissions

Revision ID: 039a56449207
Revises: d8c438e1a176
Create Date: 2025-12-26 07:34:28.593593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039a56449207'
down_revision: Union[str, None] = 'd8c438e1a176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('placement', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_submissions_placement'), 'submissions', ['placement'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_placement'), table_name='submissions')
    op.drop_column('submissions', 'placement')
    # ### end Alembic commands ###
