"""add_user_bank_accounts_table

Revision ID: 071124476b7f
Revises: 70cd1ed68acd
Create Date: 2025-12-28 22:42:52.709652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071124476b7f'
down_revision: Union[str, None] = '70cd1ed68acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_bank_account_id', sa.String(length=255), nullable=False),
    sa.Column('bank_account_last4', sa.String(length=4), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_holder_name', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bank_accounts_id'), 'user_bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_user_bank_accounts_is_default'), 'user_bank_accounts', ['is_default'], unique=False)
    op.create_index('ix_user_bank_accounts_stripe_bank_account_id', 'user_bank_accounts', ['stripe_bank_account_id'], unique=True)
    op.create_index('ix_user_bank_accounts_user_id', 'user_bank_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_bank_accounts_user_id', table_name='user_bank_accounts')
    op.drop_index('ix_user_bank_accounts_stripe_bank_account_id', table_name='user_bank_accounts')
    op.drop_index(op.f('ix_user_bank_accounts_is_default'), table_name='user_bank_accounts')
    op.drop_index(op.f('ix_user_bank_accounts_id'), table_name='user_bank_accounts')
    op.drop_table('user_bank_accounts')
    # ### end Alembic commands ###
