"""add_user_role_field

Revision ID: d4181ab6fdc9
Revises: 
Create Date: 2025-12-20 12:42:05.148089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4181ab6fdc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed submissions.status alter_column as SQLite doesn't support it well
    # and it's not needed for RBAC changes

    # Add role column with default value 'FOUNDER'
    op.add_column('users', sa.Column('role', sa.Enum('FOUNDER', 'JUDGE', 'ADMIN', name='userrole'), nullable=False, server_default='FOUNDER'))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)

    # Migrate existing data: is_superuser=True → role='ADMIN', is_superuser=False → role='FOUNDER'
    op.execute("UPDATE users SET role = 'ADMIN' WHERE is_superuser = 1")
    op.execute("UPDATE users SET role = 'FOUNDER' WHERE is_superuser = 0")

    # Drop is_superuser column after data migration
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore is_superuser column with default False
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), nullable=False, server_default='0'))

    # Migrate data back: role='ADMIN' → is_superuser=True, others → is_superuser=False
    op.execute("UPDATE users SET is_superuser = 1 WHERE role = 'ADMIN'")
    op.execute("UPDATE users SET is_superuser = 0 WHERE role != 'ADMIN'")

    # Drop role column and index
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')

    # Note: Removed submissions.status alter_column as it's not needed for RBAC rollback
    # ### end Alembic commands ###
