"""add_judge_assignments_table

Revision ID: d8c438e1a176
Revises: 727af58366ab
Create Date: 2025-12-21 23:22:12.495078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c438e1a176'
down_revision: Union[str, None] = '727af58366ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judge_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_id', 'submission_id', name='uq_judge_submission')
    )
    op.create_index(op.f('ix_judge_assignments_assigned_by'), 'judge_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_judge_assignments_id'), 'judge_assignments', ['id'], unique=False)
    op.create_index('ix_judge_assignments_judge_id', 'judge_assignments', ['judge_id'], unique=False)
    op.create_index('ix_judge_assignments_submission_id', 'judge_assignments', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_judge_assignments_submission_id', table_name='judge_assignments')
    op.drop_index('ix_judge_assignments_judge_id', table_name='judge_assignments')
    op.drop_index(op.f('ix_judge_assignments_id'), table_name='judge_assignments')
    op.drop_index(op.f('ix_judge_assignments_assigned_by'), table_name='judge_assignments')
    op.drop_table('judge_assignments')
    # ### end Alembic commands ###
