"""add_stripe_connect_fields_to_users

Revision ID: e91fb36b3230
Revises: 49d6a94d8830
Create Date: 2025-12-31 12:54:53.865445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91fb36b3230'
down_revision: Union[str, None] = '49d6a94d8830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('connect_onboarding_complete', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('connect_charges_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('connect_payouts_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('connect_onboarded_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_stripe_connect_account_id'), 'users', ['stripe_connect_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_connect_account_id'), table_name='users')
    op.drop_column('users', 'connect_onboarded_at')
    op.drop_column('users', 'connect_payouts_enabled')
    op.drop_column('users', 'connect_charges_enabled')
    op.drop_column('users', 'connect_onboarding_complete')
    op.drop_column('users', 'stripe_connect_account_id')
    # ### end Alembic commands ###
